apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "techtalksapi.fullname" . }}
  labels:
    run: {{ template "techtalksapi.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        run: {{ template "techtalksapi.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              protocol: "TCP"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "techtalksapi.fullname" . }}
                key: dbPassword

          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:8080

          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: {{ template "techtalksapi.fullname" . }}
                key: connectionString

      restartPolicy: {{ .Values.image.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.image.terminationGracePeriodSeconds }}





