---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "techtalksapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  connectionString: {{ .Values.secrets.connectionString  }}
  dbPassword: {{ .Values.secrets.dbPassword }}
