apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: nileshgule/sqlclient
    workspace: ../src/TechTalksDB
  - imageName: nileshgule/techtalksweb
    workspace: ../src/TechTalksWeb
  - imageName: nileshgule/techtalksapi
    workspace: ../src/TechTalksAPI
deploy:
  kubectl:
    manifests:
      - ../k8s/Minikube/*